add_subdirectory(clock)
add_subdirectory(fluent_widget)
add_subdirectory(fluent_window)
add_subdirectory(login)
add_subdirectory(ms_fluent_window)
add_subdirectory(settings)
add_subdirectory(split_fluent_window)
add_subdirectory(splash_screen)
if(FQW_HAS_WEBENGINE_WIDGETS)
    add_subdirectory(web_engine)
endif()
