#pragma once

#include <FluentQtWidgets/Global.h>
#include <FluentQtWidgets/Theme.h>

#include <QtCore/QString>
#include <QtGui/QColor>
#include <QtGui/QIcon>

namespace FluentQt {

enum class FluentIcon
{
    Up,
    Add,
    Bus,
    Car,
    Cut,
    IOT,
    Pin,
    Tag,
    VPN,
    Cafe,
    Chat,
    Copy,
    Code,
    Down,
    Edit,
    Flag,
    Font,
    Game,
    Help,
    Hide,
    Home,
    Info,
    Leaf,
    Link,
    Mail,
    Menu,
    Mute,
    More,
    Move,
    Play,
    Save,
    Send,
    Sync,
    Unit,
    View,
    Wifi,
    Zoom,
    Album,
    Brush,
    Broom,
    Close,
    Cloud,
    Embed,
    Globe,
    Heart,
    Label,
    Media,
    Movie,
    Music,
    Robot,
    Pause,
    Paste,
    Photo,
    Phone,
    Print,
    Share,
    Tiles,
    Unpin,
    Video,
    Train,
    AddTo,
    Accept,
    Camera,
    Cancel,
    Delete,
    Folder,
    Filter,
    Market,
    Scroll,
    Layout,
    GitHub,
    Update,
    Remove,
    Return,
    People,
    QRCode,
    Ringer,
    Rotate,
    Search,
    Volume,
    Frigid,
    SaveAs,
    ZoomIn,
    Connect,
    History,
    Setting,
    Palette,
    Message,
    FitPage,
    ZoomOut,
    Airplane,
    Asterisk,
    Calories,
    Calendar,
    Feedback,
    Library,
    Minimize,
    Checkbox,
    Document,
    Language,
    Download,
    Question,
    Speakers,
    DateTime,
    FontSize,
    HomeFill,
    PageLeft,
    SaveCopy,
    SendFill,
    SkipBack,
    SpeedOff,
    Alignment,
    Bluetooth,
    Completed,
    Constract,
    Headphone,
    Megaphone,
    Projector,
    Education,
    LeftArrow,
    EraseTool,
    PageRight,
    PlaySolid,
    BookShelf,
    Hightlight,
    FolderAdd,
    PauseBold,
    PencilInk,
    PieSingle,
    QuickNote,
    SpeedHigh,
    StopWatch,
    ZipFolder,
    Basketball,
    Brightness,
    Dictionary,
    Microphone,
    ArrowDown,
    FullScreen,
    MixVolumes,
    RemoveFrom,
    RightArrow,
    QuietHours,
    Fingerprint,
    Application,
    Certificate,
    Transparent,
    ImageExport,
    SpeedMedium,
    LibraryFill,
    MusicFolder,
    PowerButton,
    SkipForward,
    CareUpSolid,
    AcceptMedium,
    CancelMedium,
    ChevronRight,
    ClippingTool,
    SearchMirror,
    ShoppingCart,
    FontIncrease,
    BackToWindow,
    CommandPrompt,
    CloudDownload,
    DictionaryAdd,
    CareDownSolid,
    CareLeftSolid,
    ClearSelection,
    DeveloperTools,
    BackgroundFill,
    CareRightSolid,
    ChevronDownMed,
    ChevronRightMed,
    EmojiTabSymbols,
    ExpressiveInputEntry
};

FQW_API QString iconName(FluentIcon icon);
FQW_API QString iconResourceName(FluentIcon icon);
FQW_API QString iconPath(FluentIcon icon, Theme theme = Theme::Auto);
FQW_API QIcon icon(FluentIcon icon, Theme theme = Theme::Auto);
FQW_API QIcon icon(FluentIcon icon, Theme theme, const QColor &tint);
FQW_API QIcon icon(FluentIcon icon, const QColor &tint);

} // namespace FluentQt

Q_DECLARE_METATYPE(FluentQt::FluentIcon)
